# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 524501083ae5e1000633e69fcd7b0c0cbb8ab55361f0ff2b867e23dd4c131d5520c20e27e060fb93d3aa72ee3e92880192fe3895f920c166f9ab206427d62aa1

test:
  secret_key_base: d7b6605dfd8ae78f744fbf6ce6cb88f088893f084d86c3044127e0c7a8121ea38cc191b18826316dbcef2724fdac1128e6e49425ce2fad5fe6016c69a0686dc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
